# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec file for Elidia CLI.

Builds a single-file executable for the current platform.

Usage:
    pyinstaller packaging/elidia.spec

Output:
    dist/elidia  (or dist/elidia.exe on Windows)
"""
import sys
from pathlib import Path

block_cipher = None

project_root = Path(SPECPATH).parent

a = Analysis(
    [str(project_root / "elidia" / "cli" / "main.py")],
    pathex=[str(project_root)],
    binaries=[],
    datas=[],
    hiddenimports=[
        "elidia.agent.loop",
        "elidia.agent.personas",
        "elidia.agent.portal",
        "elidia.api.client",
        "elidia.api.streaming",
        "elidia.auth.keychain",
        "elidia.cache.lru",
        "elidia.cli.commands",
        "elidia.cli.pager",
        "elidia.cli.progress",
        "elidia.cli.renderer",
        "elidia.cli.repl",
        "elidia.cli.themes",
        "elidia.config.defaults",
        "elidia.config.rules",
        "elidia.config.settings",
        "elidia.creative.audio",
        "elidia.creative.display",
        "elidia.creative.image",
        "elidia.creative.local",
        "elidia.creative.video",
        "elidia.daemon.manager",
        "elidia.db.database",
        "elidia.mcp.client",
        "elidia.mcp.config",
        "elidia.mcp.registry",
        "elidia.mcp.types",
        "elidia.memory.auto",
        "elidia.memory.compaction",
        "elidia.memory.embeddings",
        "elidia.memory.outcomes",
        "elidia.memory.patterns",
        "elidia.memory.store",
        "elidia.models.adaptive",
        "elidia.models.router",
        "elidia.modes.autonomous",
        "elidia.modes.budget",
        "elidia.modes.classifier",
        "elidia.modes.consensus",
        "elidia.modes.deep_think",
        "elidia.modes.swarm",
        "elidia.modes.thinking",
        "elidia.permissions.audit",
        "elidia.permissions.manager",
        "elidia.permissions.trust",
        "elidia.rag.chunker",
        "elidia.rag.engine",
        "elidia.rag.ingest",
        "elidia.rag.portal_bridge",
        "elidia.rag.watcher",
        "elidia.research.export",
        "elidia.research.orchestrator",
        "elidia.research.sources",
        "elidia.session.history",
        "elidia.session.manager",
        "elidia.tools",
        "elidia.tools.base",
        "elidia.tools.fetch",
        "elidia.tools.filesystem",
        "elidia.tools.git",
        "elidia.tools.search",
        "elidia.tools.terminal",
        "elidia.widgets.protocol",
        "elidia.widgets.renderer",
        "elidia.workflow.engine",
        "click",
        "rich",
        "prompt_toolkit",
        "httpx",
        "h2",
        "hpack",
        "hyperframe",
        "keyring",
        "yaml",
        "sqlite_vec",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "torch",
        "diffusers",
        "transformers",
        "PIL",
        "tkinter",
        "unittest",
        "test",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="elidia",
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
